# Generated by Django 4.0 on 2022-04-10 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200, null=True)),
                ('foodcal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='getfoodinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal', to='calorie.foodcal')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='calorie.foodcal')),
            ],
        ),
    ]
